import 'dart:io';
import 'package:flutter/material.dart';
class Globals{
  static dynamic name;
  static dynamic email;
  static dynamic phoneno;
  static dynamic add1;
  static dynamic add2;
  static dynamic add3;
  static  File? profile;
  static dynamic carrier;
  static dynamic desg;
  static dynamic dob;
  static dynamic s;
  static bool Lang=false;
  static bool Lang2=false;
  static bool Lang3=false;
  static dynamic Nation;
  static dynamic course;
  static dynamic collage;
  static dynamic per;
  static dynamic passingyear;
  static dynamic company;
  static dynamic comptype;
  static dynamic role;
  static dynamic pe;
  static dynamic datejoin1;
  static dynamic datejoin2;
  static dynamic dateexit;
  static List? Skill;
  static dynamic hobby;
  static dynamic protitle;
  static dynamic C=false;
  static dynamic Cplus = false;
  static dynamic Flutter = false;
  static dynamic jobrole;
  static dynamic technologies;
  static dynamic proDescription;
  static List? Win;
  static dynamic refname;
  static dynamic refdesg;
  static dynamic refcomp;
  static dynamic declare;
  static dynamic declaredate;
  static dynamic venue;
}